Program          ::= { Instruction }

Instruction      ::= Declaration | Action | Loop | Conditional

Declaration      ::= Identifier "=" Cursor

Action           ::= MoveTo | LineTo | SetColor | Circle

MoveTo           ::= "move_to" Identifier "," Number "," Number
LineTo           ::= "line_to" Identifier "," Number "," Number
SetColor         ::= "set_color" Identifier "," Color
Circle           ::= "circle" Identifier "," Number
Cursor           ::= "cursor" Color Number "," Number
MoveBy           ::= "move_by" Number Number
LineBy           ::= "line_by" Number Number

Loop ::= "for" Identifier "in" Range "{" { Instruction } "}"
Range ::= Number "to" Number
Conditional ::= "if" Condition "{" { Instruction } "}" [ "else" "{" { Instruction } "}" ]
Condition ::= Identifier ComparisonOperator Number
ComparisonOperator ::= "==" | "!=" | "<" | ">" | "<=" | ">="

Identifier       ::= Letter { Letter | Digit }

Number           ::= Digit { Digit }
Color            ::= "red" | "blue" | "green" | "black" | "yellow"

Digit            ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
Letter           ::= "a" | "b" | "c" | ... | "z" | "A" | "B" | ... | "Z"


