
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN CIRCLE COLOR COMMA CURSOR EQ GEQ GT IDENTIFIER IF LBRACE LEQ LINE_TO LPAREN LT MOVE_BY MOVE_TO NEQ NUMBER RBRACE RPAREN SET_COLOR WHILEassign_stmt : IDENTIFIER ASSIGN NUMBERcircle : IDENTIFIER ASSIGN CIRCLE NUMBERcursor : IDENTIFIER CURSOR COLOR NUMBER NUMBERinstruction : circleprogram : instruction program_restprogram_rest : '
    
_lr_action_items = {'IDENTIFIER':([0,],[2,]),'$end':([1,4,],[0,-1,]),'ASSIGN':([2,],[3,]),'NUMBER':([3,],[4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'assign_stmt':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> assign_stmt","S'",1,None,None,None),
  ('assign_stmt -> IDENTIFIER ASSIGN NUMBER','assign_stmt',3,'p_assign_stmt','parser2.py',3),
  ('circle -> IDENTIFIER ASSIGN CIRCLE NUMBER','circle',4,'p_circle','parser2.py',3),
  ('cursor -> IDENTIFIER CURSOR COLOR NUMBER NUMBER','cursor',5,'p_cursor','parser2.py',3),
  ('instruction -> circle','instruction',1,'p_instruction','parser2.py',3),
  ('program -> instruction program_rest','program',2,'p_program','parser2.py',3),
  ('program_rest -> <empty>','program_rest',0,'p_program_rest','parser2.py',3),
]
