
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CIRCLE LINE_TO MOVE_TO NEWLINE NUMBER SET_COLOR STRINGinstruction : MOVE_TO NUMBER NUMBERinstruction : LINE_TO NUMBER NUMBERinstruction : SET_COLOR STRINGinstruction : CIRCLE NUMBER'
    
_lr_action_items = {'MOVE_TO':([0,],[2,]),'LINE_TO':([0,],[3,]),'SET_COLOR':([0,],[4,]),'CIRCLE':([0,],[5,]),'$end':([1,8,9,10,11,],[0,-3,-4,-1,-2,]),'NUMBER':([2,3,5,6,7,],[6,7,9,10,11,]),'STRING':([4,],[8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'instruction':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> instruction","S'",1,None,None,None),
  ('instruction -> MOVE_TO NUMBER NUMBER','instruction',3,'p_instruction_move_to','parser.py',8),
  ('instruction -> LINE_TO NUMBER NUMBER','instruction',3,'p_instruction_line_to','parser.py',12),
  ('instruction -> SET_COLOR STRING','instruction',2,'p_instruction_set_color','parser.py',16),
  ('instruction -> CIRCLE NUMBER','instruction',2,'p_instruction_circle','parser.py',20),
]
